# Form implementation generated from reading ui file 'noteEditUi.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_noteEdit(object):
    def setupUi(self, noteEdit):
        noteEdit.setObjectName("noteEdit")
        noteEdit.resize(561, 313)
        self.gridLayout = QtWidgets.QGridLayout(noteEdit)
        self.gridLayout.setObjectName("gridLayout")
        self.imageDisplay = QtWidgets.QLabel(parent=noteEdit)
        self.imageDisplay.setMinimumSize(QtCore.QSize(150, 150))
        self.imageDisplay.setText("")
        self.imageDisplay.setObjectName("imageDisplay")
        self.gridLayout.addWidget(self.imageDisplay, 2, 4, 1, 1)
        self.noteName = QtWidgets.QLineEdit(parent=noteEdit)
        self.noteName.setToolTipDuration(2000)
        self.noteName.setObjectName("noteName")
        self.gridLayout.addWidget(self.noteName, 1, 0, 1, 2)
        self.imageAdd = QtWidgets.QPushButton(parent=noteEdit)
        self.imageAdd.setObjectName("imageAdd")
        self.gridLayout.addWidget(self.imageAdd, 1, 4, 1, 1)
        self.noteCancel = QtWidgets.QPushButton(parent=noteEdit)
        self.noteCancel.setObjectName("noteCancel")
        self.gridLayout.addWidget(self.noteCancel, 3, 0, 1, 1)
        self.showImgPlace = QtWidgets.QPushButton(parent=noteEdit)
        self.showImgPlace.setObjectName("showImgPlace")
        self.gridLayout.addWidget(self.showImgPlace, 3, 2, 1, 1)
        self.noteSave = QtWidgets.QPushButton(parent=noteEdit)
        self.noteSave.setObjectName("noteSave")
        self.gridLayout.addWidget(self.noteSave, 3, 1, 1, 1)
        self.imageDel = QtWidgets.QPushButton(parent=noteEdit)
        self.imageDel.setObjectName("imageDel")
        self.gridLayout.addWidget(self.imageDel, 3, 4, 1, 1)
        self.tagSet = QtWidgets.QComboBox(parent=noteEdit)
        self.tagSet.setObjectName("tagSet")
        self.gridLayout.addWidget(self.tagSet, 1, 2, 1, 2)
        self.noteText = QtWidgets.QTextEdit(parent=noteEdit)
        self.noteText.setMinimumSize(QtCore.QSize(300, 0))
        self.noteText.setToolTipDuration(-1)
        self.noteText.setObjectName("noteText")
        self.gridLayout.addWidget(self.noteText, 2, 0, 1, 4)

        self.retranslateUi(noteEdit)
        QtCore.QMetaObject.connectSlotsByName(noteEdit)

    def retranslateUi(self, noteEdit):
        _translate = QtCore.QCoreApplication.translate
        noteEdit.setWindowTitle(_translate("noteEdit", "Редактирование.."))
        self.noteName.setToolTip(_translate("noteEdit", "Название заметки"))
        self.imageAdd.setText(_translate("noteEdit", "Добавить изображение"))
        self.noteCancel.setText(_translate("noteEdit", "Отменить"))
        self.showImgPlace.setText(_translate("noteEdit", ">>>"))
        self.noteSave.setText(_translate("noteEdit", "Сохранить"))
        self.imageDel.setText(_translate("noteEdit", "Удалить изображение"))
        self.tagSet.setToolTip(_translate("noteEdit", "Тег заметки"))
        self.noteText.setToolTip(_translate("noteEdit", "Текст заметки"))
        self.noteText.setHtml(_translate("noteEdit", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
