# Form implementation generated from reading ui file 'noteEditUi.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_noteEdit(object):
    def setupUi(self, noteEdit):
        noteEdit.setObjectName("noteEdit")
        noteEdit.resize(561, 313)
        self.gridLayout = QtWidgets.QGridLayout(noteEdit)
        self.gridLayout.setObjectName("gridLayout")
        self.noteName = QtWidgets.QLineEdit(parent=noteEdit)
        self.noteName.setToolTipDuration(2000)
        self.noteName.setObjectName("noteName")
        self.gridLayout.addWidget(self.noteName, 1, 0, 1, 2)
        self.imageDisplay = QtWidgets.QLabel(parent=noteEdit)
        self.imageDisplay.setMinimumSize(QtCore.QSize(300, 150))
        self.imageDisplay.setText("")
        self.imageDisplay.setObjectName("imageDisplay")
        self.gridLayout.addWidget(self.imageDisplay, 2, 3, 1, 1)
        self.imageAdd = QtWidgets.QPushButton(parent=noteEdit)
        self.imageAdd.setObjectName("imageAdd")
        self.gridLayout.addWidget(self.imageAdd, 1, 3, 1, 1)
        self.noteCancel = QtWidgets.QPushButton(parent=noteEdit)
        self.noteCancel.setObjectName("noteCancel")
        self.gridLayout.addWidget(self.noteCancel, 3, 0, 1, 1)
        self.tagSet = QtWidgets.QComboBox(parent=noteEdit)
        self.tagSet.setObjectName("tagSet")
        self.gridLayout.addWidget(self.tagSet, 1, 2, 1, 1)
        self.noteText = QtWidgets.QTextEdit(parent=noteEdit)
        self.noteText.setToolTipDuration(-1)
        self.noteText.setObjectName("noteText")
        self.gridLayout.addWidget(self.noteText, 2, 0, 1, 3)
        self.noteSave = QtWidgets.QPushButton(parent=noteEdit)
        self.noteSave.setObjectName("noteSave")
        self.gridLayout.addWidget(self.noteSave, 3, 1, 1, 1)
        self.showImgPlace = QtWidgets.QPushButton(parent=noteEdit)
        self.showImgPlace.setObjectName("showImgPlace")
        self.gridLayout.addWidget(self.showImgPlace, 3, 2, 1, 1)

        self.retranslateUi(noteEdit)
        QtCore.QMetaObject.connectSlotsByName(noteEdit)

    def retranslateUi(self, noteEdit):
        _translate = QtCore.QCoreApplication.translate
        noteEdit.setWindowTitle(_translate("noteEdit", "Редактирование.."))
        self.noteName.setToolTip(_translate("noteEdit", "Название заметки"))
        self.imageAdd.setText(_translate("noteEdit", "Добавить изображение"))
        self.noteCancel.setText(_translate("noteEdit", "Отменить"))
        self.tagSet.setToolTip(_translate("noteEdit", "Тег заметки"))
        self.noteText.setToolTip(_translate("noteEdit", "Текст заметки"))
        self.noteSave.setText(_translate("noteEdit", "Сохранить"))
        self.showImgPlace.setText(_translate("noteEdit", ">>>"))
