# Form implementation generated from reading ui file 'notesUi.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Notes(object):
    def setupUi(self, Notes):
        Notes.setObjectName("Notes")
        Notes.resize(400, 310)
        Notes.setMinimumSize(QtCore.QSize(400, 310))
        Notes.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(parent=Notes)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(12, 12, 12, 12)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.searchLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.searchLine.setObjectName("searchLine")
        self.gridLayout.addWidget(self.searchLine, 2, 0, 1, 2)
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 2, 3, 1, 1)
        self.noteList = QtWidgets.QListWidget(parent=self.centralwidget)
        self.noteList.setMinimumSize(QtCore.QSize(0, 0))
        self.noteList.setObjectName("noteList")
        item = QtWidgets.QListWidgetItem()
        self.noteList.addItem(item)
        self.gridLayout.addWidget(self.noteList, 3, 0, 2, 4)
        self.createNote = QtWidgets.QPushButton(parent=self.centralwidget)
        self.createNote.setObjectName("createNote")
        self.gridLayout.addWidget(self.createNote, 0, 0, 1, 2)
        self.tagAdd = QtWidgets.QPushButton(parent=self.centralwidget)
        self.tagAdd.setObjectName("tagAdd")
        self.gridLayout.addWidget(self.tagAdd, 0, 3, 1, 1)
        self.sortBy = QtWidgets.QComboBox(parent=self.centralwidget)
        self.sortBy.setObjectName("sortBy")
        self.sortBy.addItem("")
        self.sortBy.addItem("")
        self.gridLayout.addWidget(self.sortBy, 2, 2, 1, 1)
        Notes.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Notes)
        self.statusbar.setObjectName("statusbar")
        Notes.setStatusBar(self.statusbar)

        self.retranslateUi(Notes)
        QtCore.QMetaObject.connectSlotsByName(Notes)

    def retranslateUi(self, Notes):
        _translate = QtCore.QCoreApplication.translate
        Notes.setWindowTitle(_translate("Notes", "Заметки"))
        self.searchLine.setToolTip(_translate("Notes", "Поиск по имени"))
        __sortingEnabled = self.noteList.isSortingEnabled()
        self.noteList.setSortingEnabled(False)
        item = self.noteList.item(0)
        item.setText(_translate("Notes", "Главная"))
        self.noteList.setSortingEnabled(__sortingEnabled)
        self.createNote.setText(_translate("Notes", "Создать заметку"))
        self.tagAdd.setText(_translate("Notes", "Добавить тег"))
        self.sortBy.setItemText(0, _translate("Notes", "Алфавит"))
        self.sortBy.setItemText(1, _translate("Notes", "Дата изменения"))
